### ISSUE TITLE
import * as d3 from 'd3';

### ISSUE THREAD

**Issue by steverhodes10** [srehanuddin/angular2-d3-sample#1]
I see at the top of a your pages, but it keeps underlining it saying "cannot find module d3". can you explain what exact file we are suppose to be pulling from?

**Comment by srehanuddin** [comment]
you have to run mentioned command

`npm install`

this will install required modules for your application from package.json

`"dependencies": {
    "angular2": "2.0.0-beta.12",
    "d3": "^3.5.16",
    "d3-tip": "^0.6.7",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "^0.19.24",
    "zone.js": "^0.6.6"
  },`

For  this error "cannot find module d3", i added tsd file of d3, please pull code and try again
